### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation:

### ISSUE THREAD

**Issue by yongqianxiao** [ku2482/slac.pytorch#13]
Hello, there is a error while it updated the actor network. After I changed all the `nn.ReLU(inplace=True)` to `nn.ReLU(inplace=False)`,  and this error still exists. Anyone else meets issue?

My packages version:
python: 3.6.7
torch: 1.7.1
mujoco_py.__version__: 2.0.2.13
mujoco: 200

2022-09-16 20:13:43.759013: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/home/buduo/.mujoco/mujoco200/bin
2022-09-16 20:13:43.759029: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Updating latent variable model.: 100%|██████████| 20/20 [00:02<00:00,  6.73it/s]
/home/XYQ/KoopmanDemo/sac_ae_xiao/SLAC/slac.pytorch/slac/algo.py:183: UserWarning: Output 1 of SplitBackward is a view and is being modified inplace. This view is an output of a function that returns multiple views. Inplace operators on such views are being deprecated and will be forbidden starting from version 1.8. Consider using `unsafe_` version of the function that produced this view or don't modify this view inplace. (Triggered internally at  /pytorch/torch/csrc/autograd/variable.cpp:491.)
  action, log_pi = self.actor.sample(feature_action)
Traceback (most recent call last):
  File "/home/XYQ/KoopmanDemo/sac_ae_xiao/SLAC/slac.pytorch/train.py", line 60, in <module>
    main(args)
  File "/home/XYQ/KoopmanDemo/sac_ae_xiao/SLAC/slac.pytorch/train.py", line 48, in main
    trainer.train()
  File "/home/XYQ/KoopmanDemo/sac_ae_xiao/SLAC/slac.pytorch/slac/trainer.py", line 122, in train
    self.algo.update_sac(self.writer)
  File "/home/XYQ/KoopmanDemo/sac_ae_xiao/SLAC/slac.pytorch/slac/algo.py", line 145, in update_sac
    self.update_actor(z, feature_action, writer)
  File "/home/XYQ/KoopmanDemo/sac_ae_xiao/SLAC/slac.pytorch/slac/algo.py", line 188, in update_actor
    loss_actor.backward(retain_graph=False)
  File "/home/buduo/anaconda3/envs/drq/lib/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/buduo/anaconda3/envs/drq/lib/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256, 12]], which is output 0 of AddBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
Exception ignored in: <function _create_finalizer.<locals>.callback at 0x7f21f17c40d0>
Traceback (most recent call last):
  File "/home/buduo/anaconda3/envs/drq/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 280, in callback
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _create_finalizer.<locals>.callback at 0x7f21f17bdf28>
Traceback (most recent call last):
  File "/home/buduo/anaconda3/envs/drq/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 280, in callback
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _create_finalizer.<locals>.callback at 0x7f2129c37f28>
Traceback (most recent call last):
  File "/home/buduo/anaconda3/envs/drq/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 280, in callback
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _create_finalizer.<locals>.callback at 0x7f21f1676d08>
Traceback (most recent call last):
  File "/home/buduo/anaconda3/envs/drq/lib/python3.6/site-packages/dm_control/mujoco/wrapper/core.py", line 280, in callback
TypeError: 'NoneType' object is not callable

Process finished with exit code 1

**Comment by ku2482** [comment]
Did you try `torch==1.6.0`?

**Comment by toshikwa** [comment]
Hi @yongqianxiao 

Although I found the unnecessary inplace oparation (and fixed it), I could not reproduce your issue.
Could you pull the latest code and try again?

If you still have issues, please let me know. In that case, the issue may be related to your environment.
